[workspace]
members = ["rust_tier", "rust_tier_cli", "rust_tier_daemon"]
resolver = "3"

[workspace.dependencies]
tokio = { version = "1.44.2", features = ["full"] }

[workspace.workspace-dependencies]
rust_tier = { path = "./rust_tier" }
