[package]
name = "rust_tier"
version = "0.1.0"
edition = "2024"

[dependencies]
config = { version = "0.15.11" }
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

