[package]
name = "device"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.83"
futures = "0.3.31"
ipnetwork = "0.20.0"
pnet = "0.35.0"
tokio = { version = "1.40.0", features = ["full"] }
tun-rs = { version = "1.3.6", features = ["async"] }
